FROM python:3.12

WORKDIR /usr/src/app

COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/* .

#CMD [ "flask", "--app", "kindred", "run", "--host=0.0.0.0"]
ENTRYPOINT ["tail", "-f", "/dev/null"]